version: "3.7"
services:
  heartbeat-server:
    environment:
      - ENV
      - PORT
      - CORS_ALLOW_ORIGIN
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - DB_ROOT_PASSWORD
      - DB_HOST
      - DB_PORT
    restart: always
    tty: true
    networks:
      - heartbeat-network
networks:
  heartbeat-network:
    driver: bridge

